### ISSUE TITLE
What's the Python version on our server?

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-web-repo#11]
Because there is a different behavior between the online page and my local page: locally, under Python 3.6, the table is directly sorted by country unlike online where there is a latency (bedore the table is sorted by js).
It's the same for [the JSON](http://repo.manjaro.org/new/manjaro-web-repo/docs/status.json), it isn't sorted by country but it is on my computer...

**Comment by Huluti** [comment]
There was a change in Python 3.6.

> New dict implementation

The dict type now uses a “compact” representation based on a proposal by Raymond Hettinger which was first implemented by PyPy. The memory usage of the new dict() is between 20% and 25% smaller compared to Python 3.5.

The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon (this may change in the future, but it is desired to have this new dict implementation in the language for a few releases before changing the language spec to mandate order-preserving semantics for all current and future Python implementations; this also helps preserve backwards-compatibility with older versions of the language where random iteration order is still in effect, e.g. Python 3.5).

**Comment by Kirek** [comment]
You can use OrderectDict

**Comment by Huluti** [comment]
I think this is what I'll do.

**Comment by Huluti** [comment]
Fixed b3260fe44a39f91c21ddd8e08474e261174bf95b.
