### ISSUE TITLE
Create a .conf file

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-web-repo#12]
Currently most of the code is hard-coded. Having a configuration file might help development and usability on the server.

**Comment by Huluti** [comment]
We have a conf.py file. Do you want that I make an ini file?

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/manjaro-web-repo/commit/5f6f7f45434bf7cb53619d63273012d4a48f4efe
