### ISSUE TITLE
Handle HTTPS mirrors

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-web-repo#13]
How to manage? Replace all HTTP mirrors that have a HTTPS version?

**Comment by philmmanjaro** [comment]
First list all server supporting https and then we think about it.

**Comment by Huluti** [comment]
physkets have done [this list](https://forum.manjaro.org/t/https-mirrors-not-listed/15006/14?u=huluti).

**Comment by Huluti** [comment]
Any news?

**Comment by philmmanjaro** [comment]
Well, we can list those https servers also. However I'd like to have them in one line, instead of listing the mirrors double. Some like: protocols: http, https, rsync

**Comment by Huluti** [comment]
Should not we just replace the http version with the HTTPS version if available?

**Comment by Huluti** [comment]
Many HTTPS sites have a redirection from HTTP, so it is useful to keep the HTTP version listed.

**Comment by philmmanjaro** [comment]
Well, we have several **protocols** for each mirror. Some even support **rsync**. It would be good to list those similar as Archlinux [does](https://www.archlinux.org/mirrors/). That is all. For **pacman-mirrors** it is a complete different story. I simply don't want to list all mirrors for each supported protocol in a new line.

**Comment by Huluti** [comment]
Great, I'll work on this.

**Comment by Huluti** [comment]
Which version should be used in the URL column?

**Comment by Huluti** [comment]
I've made a commit 3f440670b109ca4318eb7c62d9086ee748010751. Each mirror in the JSON file has now a "protocols" property. I just have to add rsync support for mirrors that support it, but I don't know wich..

**Comment by Huluti** [comment]
@philmmanjaro This is the last missing thing, after that the soft will be ready to enter in production.

**Comment by oberon2007** [comment]
Impressive work once more, @Huluti ! Thank you! :smiley:

**Comment by Huluti** [comment]
Thank's! ;)

**Comment by philmmanjaro** [comment]
All servers supporting **https** also support **http**. So why do we have now mixed views?

**Comment by Huluti** [comment]
Because some of them have a redirection.

**Comment by philmmanjaro** [comment]
Makes sense. Do we have still open topics or is **v1.0** now ready to replace **repo.manjaro.org** now?

**Comment by Huluti** [comment]
It's ok for me. Just maybe indicates rsync servers, but it could be after if you want.

**Comment by philmmanjaro** [comment]
Well, is **v1.0** now feature ready and can replace the current **wt** application or not. I think we offer now more options as the old code does. Everything else can be added in a point-release anyway.

**Comment by Huluti** [comment]
I'm agree.

**Comment by philmmanjaro** [comment]
Review the code once more and I consider to replace the **wt** code by tomorrow evening.
