### ISSUE TITLE
Check last sync calculation

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-web-repo#14]
Seems some is off with the last sync calculation. Mirror **netzspielplatz** for example syncs every 5 minutes, so at least that mirror can't be last synced more than 5 minutes ago ...

**Comment by Huluti** [comment]
Ok, i'm working on this. Thank's.

**Comment by Huluti** [comment]
See http://mirror.netzspielplatz.de/manjaro/packages/state: the date is date=2017-01-30T16:26:52Z : > 1h...

**Comment by Huluti** [comment]
Still again date=2017-01-30T19:16:56Z. Are you sure that it is synced every 5 minutes?

**Comment by Huluti** [comment]
For me, the last sync time is working according to the state file, but maybe I have make an error and I don't see..

**Comment by oberon2007** [comment]
Something is strange with that sync file. Right now it's showing 19:26 for me, so just ten minutes later than it did show for you 10 minutes earlier (from now) - so this doesn't make sense, if you see what I mean :wink:

**Comment by oberon2007** [comment]
Also, why is http://www.uex.dk with a sync time of over a day sorted before the ones with sync times of shortly over one hour?

**Comment by Huluti** [comment]
Really strange...

**Comment by Huluti** [comment]
@philmmanjaro an idea?

**Comment by philmmanjaro** [comment]
@Huluti: how do you display the time? If the state file has for example **date=2017-02-05T14:08:23Z** this is **14:08:23 UTC**. In Germany we have **15:08:23 UTC+1**. That is why you are off by one hour. With summer time you might be off by two hours with the current calculation.

**Comment by philmmanjaro** [comment]
It would be better to use the **state** files provided in **/var/repo/repo** folder of the server as base instead of **date** to do a calculation ...

**Comment by Huluti** [comment]
I've made this commit: ee1790b5fe16d51385de4d13174241d8e8f529e1. I'm waiting to see results.

I haven't understant what you mean in your last message. We have to compare the current datetime to the state's datetime, no?

**Comment by philmmanjaro** [comment]
The server provides the original state files also. It is located at **/var/repo/repo/**. However, the current source seems to have it fixed. It depends now if summer time was calculated also. For now it works.

**Comment by Huluti** [comment]
I have made a commit to really fix last sync calculation: bd01ba87424bc0b083c7eaab3f8b24e75baadbf8.
