### ISSUE TITLE
sorting function should be more obvious

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-web-repo#15]
When you mouseover the column headers the mouse pointer currently doesn't suggest that they are clickable.
I think the functionality like this is not obvious at all.
If the cursor cannot be made to suggest a link maybe it will be good to add some arrow up/down icons to signal the search function, or the headers could highlight with a different font color are similar action?

**Comment by Huluti** [comment]
There are already icons but since the pull of the repo and the regeneration is not done in same time and I have made some changes...
But, I have changed the mouse cursor a112e3a16f0b1fbef4b050d4e80f102ba8cb4968. Thank's!

**Comment by oberon2007** [comment]
> There are already icons

I appear to not see the latest version then... Not here? http://repo.manjaro.org/new/manjaro-web-repo/docs/index.html
![](http://imgur.com/i1deR1Yl.png)

**Comment by Huluti** [comment]
Should be there now.

**Comment by oberon2007** [comment]
hm. not for me
![](http://imgur.com/s7tkXrE.png)
Also as you can see the sorting by sync time is still off, aswell as the sync time itself.

**Comment by Huluti** [comment]
For sync time view #14.
