### ISSUE TITLE
How to minimize pressure on mirror servers

### ISSUE THREAD

**Issue by fhdk** [manjaro/manjaro-web-repo#16]
I am throwing an idea I saw [Archlinux](https://wiki.archlinux.org/index.php/DeveloperWiki:NewMirrors)
They reference [this script](https://git.server-speed.net/users/flo/bin/tree/syncrepo.sh) as a starting point

How simple would it be implement a similar file with an epoch timestamp every time a statefile changes?

**Comment by Huluti** [comment]
I think this issue is more related to https://github.com/manjaro/boxit.
