### ISSUE TITLE
Why Africa instead of South Africa?

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-web-repo#18]
Why this mirror http://mirror.is.co.za/mirrors/manjaro.org/ is labelled as Africa instead of South Africa?

**Comment by philmmanjaro** [comment]
For years nobody cared about it. We can change it to South Africa. I've no objections on it.

**Comment by Huluti** [comment]
It's more logical. 0a8b6b8d7383df98b4f77d062843ff96d0316cf0
