### ISSUE TITLE
Prepare release

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-web-repo#19]
@philmmanjaro for me all is fine, just think to change the url of the **mirrors.json** file in **conf.py**.

**Comment by philmmanjaro** [comment]
Sure. I'll do the switch on Friday or so. Will keep you informed.

**Comment by Huluti** [comment]
Take your time ;)

**Comment by philmmanjaro** [comment]
@Huluti: this is now our tree-view:

```
repo.manjaro.org:
.
├── AUTHORS
├── COPYING
├── data
│   ├── css
│   │   └── style.css
│   ├── footer.html
│   ├── header.html
│   ├── img
│   │   ├── asc.png
│   │   ├── desc.png
│   │   ├── manjaro.png
│   │   ├── out.png
│   │   ├── sort.png
│   │   ├── unknown.png
│   │   └── up.png
│   └── js
│       └── main.js
├── docs
│   ├── data -> ../data
│   ├── index.html
│   ├── mirrors.json -> ../mirrors.json
│   └── status.json
├── logs
│   ├── access.log
│   ├── error.log
│   └── wt.log
├── mirrors.json
├── README.md
└── src
    ├── builder.py
    ├── conf.py
    ├── helpers.py
    ├── main.py
    ├── mirror.py
    └── __pycache__
        ├── builder.cpython-32.pyc
        ├── conf.cpython-32.pyc
        ├── helpers.cpython-32.pyc
        └── mirror.cpython-32.pyc

9 directories, 30 files
```
I had to create two symlinks to **data** and **mirrors.json** to get it working as **docs** is our root-folder for **repo.manjaro.org**. Is it possible to a logging feature to log errors in **logs/errors.log** and a minimal log-output to **logs/mwr.log**?

**Comment by Huluti** [comment]
Great @philmmanjaro. It was in the plans, I'll take care of it.

**Comment by philmmanjaro** [comment]
@Huluti: Thx. Also write me a short summary we can use for our blog as announcement for the new rewrite of our mirror-check service. What the new features are and what the idea was behind it to do a rewrite in general.

**Comment by Huluti** [comment]
Okay, I'll give it to you this afternoon.

**Comment by philmmanjaro** [comment]
No rush. Take your time.
