### ISSUE TITLE
Brasilian server not listed

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-web-repo#20]
https://github.com/manjaro/pacman-mirrors/blob/master/data/mirrors/Brasil is not showing for some reason.

**Comment by Huluti** [comment]
The only reason is that the server has an issue, and in the current version the mirrors that have an issue are not shown. It's the next thing, I'll work: do an other table like in https://www.archlinux.org/mirrors/status/ to show the errors.

**Comment by oberon2007** [comment]
ah. I didn't know that the server has issues.

**Comment by Huluti** [comment]
@philmmanjaro I've made a commit b6d24c6a80317ebb3143529c5fd3d2d70fd9b8a8 but I didn't know that it will goes in production. All is working, but it isn't good to push latest commits direclty in prod. Should we use release tags?
@oberon2007 now the Brasil mirror is shown ;).

**Comment by philmmanjaro** [comment]
All changes go to production as of now. We still sync every hour our git repo on our repo.manjaro.org server to match your work at github. We can create a branch called **development** were you can work and push when ready back to **master**.

**Comment by Huluti** [comment]
Okay, I'll do that.
