### ISSUE TITLE
We have to be sure the repos are the same as before with the new pacman-mirrors v4

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-web-repo#26]
@philmmanjaro could you take a look and maybe migrate changes from https://github.com/manjaro/pacman-mirrors/commit/ba94169b72f8a5fbc6abe0f6c594cada2b793cef here. I'm not sure about that, so I let you decide.

**Comment by philmmanjaro** [comment]
[Read](https://github.com/manjaro/manjaro-web-repo/commit/42048db4677bd1fa6b92f71d178225f288cc3150) before you post some :smile:

**Comment by Huluti** [comment]
Good! I just wanted to be sure that all was good. 👍
