### ISSUE TITLE
Are FTP servers useful ?

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-web-repo#38]
It seems that Debian has dropped the ftp protocol for its servers. Does Manjaro have any use?

Source: https://www.theregister.co.uk/2017/04/27/debian_to_turn_off_ftp/

**Comment by fhdk** [comment]
Personally I don't use ftp and I never had. Don't know why really.

But it could be that for unknown reasons - one could think of censorship blocking http access to everything except approved sites - some users only have the possibility of updating their systems through FTP.

**Comment by philmmanjaro** [comment]
Addopted as Ticket# 86122
