### ISSUE TITLE
Make table sort-able

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-web-repo#4]

**Comment by kainonergon** [comment]
It would be nice not only to sort the table, but also to apply filters.

**Comment by philmmanjaro** [comment]
d5ad18979f6e7bae400ba21e41c0dc7cf302dfc6

**Comment by Huluti** [comment]
I'm working on filters.

**Comment by Huluti** [comment]
Fixed with a448525dd3ee329783cbc637de21fbc8d788c154 and d2c4e35eba2193f4a9e2f17dff83a99210856241.

**Comment by kainonergon** [comment]
When sorting by last sync some outdated mirrors are listed first instead of last.

**Comment by Huluti** [comment]
I'm working on that. ;)
