### ISSUE TITLE
Packages page for Manjaro

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-web-repo#42]
@philmmanjaro If we want a packages page (like https://www.archlinux.org/packages) like you asked me some time ago, how can we start? From the web server, can I get the list of the packages? Maybe, I could have access to the web server. What do you think?

**Comment by philmmanjaro** [comment]
@Huluti: we might need to see on how we can manage that with sane user rights. Can you create a local repository and make a mockup application based on that one? We may use then git as we do with web-repo application when the concept is there. For creating the app I don't think full access is needed, however a fake repo structure would be enough. You may check here: http://repo.manjaro.org.uk/

**Comment by Huluti** [comment]
I have some questions that come in my mind. 
For me, we have at least two options for the app :
- It could be part of this repo. This could be achived by getting list of packages each x minutes (as mirrors), then generate a static file (packages.html) in the docs folder and add some options in javascript.
- It could be a new  app in PHP (or any server language) which allows more flexibility in data processing (non-static).

Do you have an opinion on the subject?

**Comment by philmmanjaro** [comment]
I'm open for both options. The later might make more sense ...

**Comment by philmmanjaro** [comment]
I created a new ticket for it (Ticket# 86121)
