### ISSUE TITLE
At least testing is switched for unstable

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-web-repo#5]
For example check http://ftp.tu-chemnitz.de in our current **mirror check service**.

**Comment by philmmanjaro** [comment]
If you check http://mirror.ventraip.net.au it seems also **stable** is switched. So we have to check that routine again ...

**Comment by Huluti** [comment]
I'll check.

**Comment by Huluti** [comment]
I've made a commit. Can you retry?

**Comment by philmmanjaro** [comment]
Fixed via a33fe4c3ed492f69370ca5a81cd0786596fbe2ea
