### ISSUE TITLE
index.html should be stored in docs folder

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-web-repo#6]
To have maximum security we should create a **docs** folder, which includes the final index.html and other needed files. Application and data files should be stored in a different folder. This makes it more secure as the root folder will start with **docs** as all other webapplications do ...

**Comment by Huluti** [comment]
I've moved generated files in an output folder.

**Comment by philmmanjaro** [comment]
Ok, works now: https://github.com/manjaro/manjaro-web-repo/commit/2ed0219231a697d623706dbf2bb8e071a4d71c9c

**Comment by Huluti** [comment]
This url is not good anymore: http://repo.manjaro.org/new/manjaro-web-repo/index.html

**Comment by philmmanjaro** [comment]
I created a symlink to the new one aswell. Should work both now.

**Comment by Huluti** [comment]
But paths for http://repo.manjaro.org/new/manjaro-web-repo/index.html aren't good. CSS, JS and iamges aren't loaded.
