### ISSUE TITLE
On screen explanations or labels

### ISSUE THREAD

**Issue by jsamyth** [manjaro/manjaro-web-repo#8]
What do the shading colors actually mean?  (Colors are too muted, should be more bold).
What does a check mark or an X mean?  (Not up to date?  Not supported?  Unreachable?)

How about a "ping them" button and ping column column to get an idea about speed **from the users location** by sending 3 to 5 pings to each. 

Frankly, the old mirror list had more functionality.

**Comment by Huluti** [comment]
I've added tooltips on the icons: 25df74460007e36184ff1a39caca546c8819efa4.

> How about a "ping them" button and ping column column to get an idea about speed from the users location by sending 3 to 5 pings to each.

It's the job of [pacman-mirrors.](https://github.com/manjaro/pacman-mirrors)

> Frankly, the old mirror list had more functionality.

Keep in-mind that is a work-in-progress.
