### ISSUE TITLE
JSON data file

### ISSUE THREAD

**Issue by fhdk** [manjaro/manjaro-web-repo#9]
Very nice layout - reasonable color choice - and the marking of the servers is in a way that makes them equally good.

Some requested a sorting feature - no need if you could implement a status file of all mirrors.

* It would be a releif for all mirror servers
* It would be possible to make a `--top` parameter for pacman-mirrors - valueable for installers

`status.json`
```
[
    {
        "country": "Germany",
        "response_time": "0.123",
        "last_sync": "01:30",
        "url": "http://mirror.domain.tld/manjaro"
    },
    {
        "country": "Germany",
        "response_time": "0.123",
        "last_sync": "01:30",
        "url": "http://mirror.domain.tld/manjaro"
    },
[
```

**Comment by Huluti** [comment]
[Already implemented.](http://repo.manjaro.org/new/manjaro-web-repo/status.json)
